// prisma/merge.js

const fs = require('fs');
const path = require('path');

const prismaDir = __dirname;
const basePath = path.join(prismaDir, 'base.prisma');
const modelsDir = path.join(prismaDir, 'models');
const schemaPath = path.join(prismaDir, 'schema.prisma');

function mergePrismaSchema() {
  if (!fs.existsSync(basePath)) {
    console.error('base.prisma not found in prisma/ directory.');
    process.exit(1);
  }

  if (!fs.existsSync(modelsDir)) {
    console.error('models/ directory not found in prisma/.');
    process.exit(1);
  }

  const baseContent = fs.readFileSync(basePath, 'utf8');

  const modelFiles = fs
    .readdirSync(modelsDir)
    .filter((file) => file.endsWith('.prisma'))
    .sort(); // deterministic order

  const modelsContent = modelFiles
    .map((file) => {
      const fullPath = path.join(modelsDir, file);
      const content = fs.readFileSync(fullPath, 'utf8').trim();
      return `// --- ${file} ---\n\n${content}\n`;
    })
    .join('\n\n');

  const finalSchema = `${baseContent.trim()}

// AUTO-GENERATED FROM prisma/models/*.prisma
// DO NOT EDIT THIS FILE DIRECTLY

${modelsContent}
`;

  fs.writeFileSync(schemaPath, finalSchema, 'utf8');
  console.log('✅ prisma/schema.prisma generated from prisma/base.prisma + prisma/models/*.prisma');
}

mergePrismaSchema();
